version: '3'

services:

  db:
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: db 
    restart: always
    tty: true
    volumes: 
      - mysqlvolume:/var/lib/mysql
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=desafionode
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafionetwork

  nginx:
    image: nginx:1.15.0-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/myNginxServer.conf:/etc/nginx/conf.d/default.conf
    networks:
      - desafionetwork
  
  app:
    image: pedrozonta21/desafio-node
    entrypoint: dockerize -wait tcp://db:3306 -wait tcp://nginx:80 node index.js
    networks:
      - desafionetwork
    ports:
      - "3000:3000"
    depends_on:
      - db
      - nginx

volumes:
  mysqlvolume:

networks:
  desafionetwork:
    driver: bridge