version: '3'

services:

  db:
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: db 
    restart: always
    tty: true
    volumes: 
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=desafionode
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafionetwork

  nginx:
    image: nginx:1.15.0-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/myNginxServer.conf:/etc/nginx/conf.d/default.conf
    networks:
      - desafionetwork
    depends_on:
      - app
  
  app:
    build:
      context: .
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install & node index.js" 
    volumes:
      - ./:/usr/src/app
      # - /usr/src/app/node_modules # volume anonimo
    networks:
      - desafionetwork
    depends_on:
      - db

networks:
  desafionetwork:
    driver: bridge